[versions]
# libraries
junit = "4.13.2"
ollama4j = "1.0.87"
opentest4j = "1.3.0"
jupiter = "5.11.3"

# plugins
changelog = "2.2.1"
intelliJPlatform = "2.1.0"
kotlin = "2.0.21"
kover = "0.8.3"
qodana = "2024.2.6"

[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }
ollama4j = { group = "io.github.ollama4j", name = "ollama4j", version.ref = "ollama4j" }
opentest4j = { group = "org.opentest4j", name = "opentest4j", version.ref = "opentest4j" }
jupiter = { group = "org.junit.jupiter", name = "junit-jupiter-api", version.ref = "jupiter" }

[plugins]
changelog = { id = "org.jetbrains.changelog", version.ref = "changelog" }
intelliJPlatform = { id = "org.jetbrains.intellij.platform", version.ref = "intelliJPlatform" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
qodana = { id = "org.jetbrains.qodana", version.ref = "qodana" }
